global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'whispr-messaging'
    static_configs:
      - targets: ['messaging-service:4000']
        labels:
          service: 'messaging'
          env: 'dev'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
