apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: whispr-prod

resources:
  - ../../base

replicas:
  - name: messaging-service
    count: 2

images:
  - name: ghcr.io/whispr-messenger/messaging-service
    newTag: latest

configMapGenerator:
  - name: messaging-service-config
    behavior: merge
    literals:
      - PHX_HOST=whispr.io
      - POOL_SIZE=10
